# @format
os: linux
dist: focal
language: node_js
node_js:
  - 18

branches:
  only:
    - master

before_install:
  - npm --version

install:
  - npm install
  - sudo apt-get install -y imagemagick graphicsmagick

jobs:
  include:
    - script:
        - npm run eslint
      name: 'Lint code sources'
    - script:
        - npm run test-unit
      name: 'Unit test'
    - script:
        - npm run test-functional
      name: 'Functional test'
    - script:
        - npm audit --audit-level=critical
      name: 'Lightweight dependencies security audit'
    - script:
        - npm run test-links
      name: 'Markdown link checks'
    - script:
        - node ./test/docs.js
      name: 'Documentation generation'
