# @format
os: linux
dist: focal
language: node_js
node_js:
  - 16

branches:
  only:
    - master

before_install:
  - npm --version

install:
  - npm install

jobs:
  include:
    - script:
        - npm run assert-code
      name: 'Lint, build and test'
    - script:
        - npm audit --audit-level=moderate
      name: 'Lightweight dependencies security audit'
    - script:
        - npm run validate-links
      name: 'Markdown link checks'
